### ISSUE TITLE
RuntimeError: inverse: LAPACK library not found in compilation

### ISSUE THREAD

**Issue by CGMikeG** [abdallahdib/NextFace#48]
Little help, please. I am getting below error.

(nextface) E:\GITHUB\NEXTFACE\NextFace>python optimizer.py --sharedIdentity --input input/s2.png --output output/
loading optim config from:  ./optimConfig.ini
[WARN] no cuda enabled device found. switching to cpu...
Loading Basel Face Model 2017 from ./baselMorphableModel/morphableModel-2017.pickle...
loading mesh normals...
loading uv parametrization...
loading landmarks association file...
creating sampler...
C:\Anaconda\envs\nextface\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\b\abs_f0dma8qm3d\croot\pytorch_1669187301762\work\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
loading image from path:  input/s2.png
detecting landmarks using: mediapipe
E:\GITHUB\NEXTFACE\NextFace\landmarksmediapipe.py:55: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  C:\b\abs_f0dma8qm3d\croot\pytorch_1669187301762\work\torch\csrc\utils\tensor_new.cpp:204.)
  return torch.tensor(landmarks, device = self.device)
init camera pose...
1/3 => Optimizing head pose and expressions using landmarks...
100%|██████████████████████████████████████████████████████████████████████████████████| 2000/2000 [01:36<00:00, 20.71it/s]
2/3 => Optimizing shape, statistical albedos, expression, head pose and scene light...
  0%|                                                                                              | 0/401 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "optimizer.py", line 486, in <module>
    optimizer.run(inputDir,
  File "optimizer.py", line 434, in run
    self.runStep2()
  File "optimizer.py", line 242, in runStep2
    images = self.pipeline.render(cameraVerts, diffuseTextures, specularTextures)
  File "E:\GITHUB\NEXTFACE\NextFace\pipeline.py", line 134, in render
    scenes = self.renderer.buildScenes(cameraVerts, self.faces32, normals, self.uvMap, diffuseTextures,
  File "E:\GITHUB\NEXTFACE\NextFace\renderer.py", line 126, in buildScenes
    cam =  self.setupCamera(focal[i], self.screenWidth, self.screenHeight)
  File "E:\GITHUB\NEXTFACE\NextFace\renderer.py", line 81, in setupCamera
    cam = pyredner.Camera(
  File "C:\Anaconda\envs\nextface\lib\site-packages\pyredner\camera.py", line 118, in __init__
    self.intrinsic_mat_inv = torch.inverse(self.intrinsic_mat).contiguous()
RuntimeError: inverse: LAPACK library not found in compilation

**Comment by abdallahdib** [comment]
please verify ur installation. re-install pytorch and follow the commands in INSTALL file
