### ISSUE TITLE
No face was found in this image

### ISSUE THREAD

**Issue by kenmaxnejp** [abdallahdib/NextFace#49]
Dear all, 
NextFace complained about cannot find any face in the image. I tried to save the image as jpg or png but it didn't work. I even tried to
use your image in Github but without any luck. Sorry it looks like a stupid question but I just don't know how to solve it.

(faceNext) C:\Users\kenmax\NextFace>python optimizer.py --input c:\Users\kenmax --output c:\Users\kenmax\hikari
loading optim config from:  ./optimConfig.ini
Loading Basel Face Model 2017 from ./baselMorphableModel/morphableModel-2017.pickle...
loading mesh normals...
loading uv parametrization...
loading landmarks association file...
creating sampler...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
loading images from path:  c:\Users\kenmax
loading image from path:  c:\Users\kenmax/hikari03.png
[INFO] resizing input image to fit: 256 px resolution...
detecting landmarks using: mediapipe
Traceback (most recent call last):
  File "optimizer.py", line 491, in <module>
    doStep3= doStep3)
  File "optimizer.py", line 420, in run
    self.setImage(imagePathOrDir, sharedIdentity)
  File "optimizer.py", line 128, in setImage
    landmarks = self.landmarksDetector.detect(self.inputImage.tensor)
  File "C:\Users\kenmax\NextFace\landmarksmediapipe.py", line 51, in detect
    land = self._detect((images[i].detach().cpu().numpy() * 255.0).astype('uint8'))
  File "C:\Users\kenmax\NextFace\landmarksmediapipe.py", line 71, in _detect
    raise RuntimeError('No face was found in this image')
RuntimeError: No face was found in this image

(faceNext) C:\Users\kenmax\NextFace>

**Comment by abdallahdib** [comment]
that means that the face detector failed to detect a face in the image. in such case, nextface cannot run. u may want to try with other images

**Comment by kunyao** [comment]
Hi, I met with the same issue, but later on, I figure out that my folder contains a hidden system file(.DS_Store). The image loader somehow loads every file in the input dir including non-image type and generates a zero tensor. Simply deleting the files should work. For the loader, it'd be helpful to add a warning of non-image input to avoid this confusion.

**Comment by ggxxii** [comment]
> that means that the face detector failed to detect a face in the image. in such case, nextface cannot run. u may want to try with other images

I've tried your provided images, but encounter the same issue. I'm using Fan detection.
