### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by DeXtmL** [abdallahdib/NextFace#52]
Clean Conda installation and Win64,
I get this:

PackagesNotFoundError: The following packages are not available from current channels:

  - redner-gpu==0.4.25=pypi_0
  - tifffile==2020.9.3=pypi_0
  - networkx==2.5.1=pypi_0
  - pillow==8.4.0=pypi_0
  - decorator==4.4.2=pypi_0
  - pytorch==1.3.1=py3.6_cuda101_cudnn7_0
  - imageio==2.15.0=pypi_0
  - scikit-image==0.17.2=pypi_0
  - scipy==1.5.4=pypi_0
  - face_alignment==1.2.0=py_1
  - pyparsing==3.0.7=pypi_0
  - torchvision==0.4.2=py36_cu101
  - mediapipe==0.8.3

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by bboylalu** [comment]
I got it running with the commands in the INSTALL file, not the environment.yml, but these were the issues:
- torchvision==0.4.2 is not in the pytorch channel anymore [https://anaconda.org/pytorch/pytorch/files?page=13] (I suppose it was removed). Closest one is:
`conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.1 -c pytorch`
- I couldn't install mediapipe because it couldn't build opencv-python, as it tried to install the latest version which dropped support for Python 3.6.* (the one INSTALL mentions). Maybe you can update to Python 3.7, but what I did was:
`pip install opencv-python==4.6.0.66`
which is the last version to support Python 3.6.* and afterwards I installed mediapipe with
`pip install mediapipe`.
If you're going for FAN I think this isn't required at all, but maybe it helps someone.
Maybe they are not the most elegant solutions, but I've got my *.OBJ file.

**Comment by valador** [comment]
# 1.13.1 not support 11.8, need python 3.9
conda install -n faceNext --yes -c pytorch -c nvidia \
    pytorch==1.13.1 \
    torchvision \
    pytorch-cuda=11.7 \
    cudatoolkit=11.7

# not support py39, only for python 3.8, build from source?
RUN conda run -n faceNext pip3 install redner-gpu
conda install -n faceNext --yes -c conda-forge opencv
# >1.2 have AttributeError: _3D
conda install -n faceNext --yes -c 1adrianb face_alignment==1.2
conda install -n faceNext --yes -c anaconda h5py
conda run -n faceNext pip3 install mediapipe
conda run -n faceNext pip3 install mitsuba
# > 1.22.3 have error, need code update
conda install -n faceNext--yes -c conda-forge numpy==1.22.3

**Comment by GuyPaddock** [comment]
Related to this issue, I was getting this error when trying to install packages:
```
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

It looks like mediapipe no longer publishes a Python 3.6 package, and NextFace uses Python 3.6. The lowest version currently available is for Python 3.8. I changed the `INSTALL` commands to the following:
```
conda create --name faceNext python=3.8
conda activate faceNext
conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.1 -c pytorch
pip install redner-gpu
conda install -c conda-forge opencv
conda install -c 1adrianb face_alignment=1.2.0
conda install -c anaconda h5py
pip install mediapipe
```

That gets me past install, but it looks like the way numpy handles delimiters has changed, per https://github.com/numpy/numpy/issues/22311 because I'm getting this error:
```
Traceback (most recent call last):
  File "optimizer.py", line 489, in <module>
    optimizer = Optimizer(outputDir, config)
  File "optimizer.py", line 21, in __init__
    self.pipeline = Pipeline(self.config)
  File "/home/guyep/playground/NextFace/pipeline.py", line 26, in __init__
    self.morphableModel = MorphableModel(path = config.path,
  File "/home/guyep/playground/NextFace/morphablemodel.py", line 150, in __init__
    self.landmarksAssociation = torch.tensor(np.loadtxt(pathLandmarks, delimiter='\t\t')[:, 1].astype(np.int64)).to(device)
  File "/home/guyep/miniconda3/envs/faceNext/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/guyep/miniconda3/envs/faceNext/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in _read
    arr = _load_from_filelike(
TypeError: Text reading control character must be a single unicode character or None; but got: '\t\t'
```

**Comment by Kazioo** [comment]
The easiest way seems to be downloading a wheel of older Mediapipe that is python 3.6 compatible [like this one](https://files.pythonhosted.org/packages/3a/26/c3a66df4ad46824171b22180aeab24452bfc3f7384dadaedb654d7d2aef2/mediapipe-0.8.0-cp36-cp36m-win_amd64.whl)

Then use:
`pip install mediapipe-0.8.0-cp36-cp36m-win_amd64.whl`

If you get pickle issues:

`pip install pickle5==0.0.10`

and change 
`import pickle`
to
`import pickle5 as pickle`
In every file that causes error.
