### ISSUE TITLE
face_alignment installation issues

### ISSUE THREAD

**Issue by yosun** [abdallahdib/NextFace#59]
conda install face_alignment did not work so i tried pip install, but this issue arises

Loading Basel Face Model 2017 from ./baselMorphableModel/morphableModel-2017.pickle...
loading mesh normals...
loading uv parametrization...
loading landmarks association file...
creating sampler...
Traceback (most recent call last):
  File "optimizer.py", line 489, in <module>
    optimizer = Optimizer(outputDir, config)
  File "optimizer.py", line 25, in __init__
    self.landmarksDetector = LandmarksDetectorFAN(self.pipeline.morphableModel.landmarksMask, self.device)
  File "/home/yc/testing3dai/NextFace/landmarksfan.py", line 18, in __init__
    self.landmarksDetector = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False, device=self.device)
  File "/home/yc/anaconda3/lib/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: _3D

**Comment by yosun** [comment]
specifically pip install face-alignment==1.2 seems to solve the problem

perhaps considering upgrading to face-alignment 1.4
