### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by aadeshrao123** [abdallahdib/NextFace#65]
`(faceNext) C:\Users\aades\Music\testthings\NextFace>python optimizer.py --sharedIdentity --input C:\Users\aades\Downloads\face --output C:\Users\aades\Downloads\New\
loading optim config from:  ./optimConfig.ini
[WARN] no cuda enabled device found. switching to cpu...
Loading Basel Face Model 2017 from ./baselMorphableModel/morphableModel-2017.pickle...
loading mesh normals...
loading uv parametrization...
loading landmarks association file...
creating sampler...
C:\Users\aades\miniconda3\envs\faceNext\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
loading images from path:  C:\Users\aades\Downloads\face
loading image from path:  C:\Users\aades\Downloads\face/cvb.png
loading image from path:  C:\Users\aades\Downloads\face/xcvb.png
detecting landmarks using: fan
C:\Users\aades\Music\testthings\NextFace\landmarksfan.py:35: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  return torch.tensor(landmarks, device = self.device)
init camera pose...
1/3 => Optimizing head pose and expressions using landmarks...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:25<00:00, 79.96it/s]
2/3 => Optimizing shape, statistical albedos, expression, head pose and scene light...
  0%|                                                                                                            | 0/401 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "optimizer.py", line 495, in <module>
    doStep3= doStep3)
  File "optimizer.py", line 438, in run
    self.runStep2()
  File "optimizer.py", line 241, in runStep2
    diffuseTextures = self.pipeline.morphableModel.generateTextureFromAlbedo(diffAlbedo)
  File "C:\Users\aades\Music\testthings\NextFace\morphablemodel.py", line 171, in generateTextureFromAlbedo
    texture = (baryCenterWeights[:, neighboors, None] * albedo[:, self.faces[oFaces[:, None], neighboors]]).sum(dim=-2)
IndexError: index 28597 is out of bounds for dimension 0 with size 28588`

**Comment by antoinersw** [comment]
Hello, i have the exact same error

1. I didnt receive any mail from through the form where is located in the 2017 model. Unfortunately logins are not shared bewteen 2019 and 2017 websites. 
2. I downloaded the 2019 model which i renamed with the 2017 name.
3. I exectuted the python optimizer.py --input "./input/s2.png" --output "./output/" 
4. error as described.

Can you help please ?
