### ISSUE TITLE
RuntimeError...Encountered a CUDA error...

### ISSUE THREAD

**Issue by danzelus** [abdallahdib/NextFace#70]
win 11, 4090

```
C:\NextFace\landmarksfan.py:35: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_new.cpp:233.)
  return torch.tensor(landmarks, device = self.device)
init camera pose...
1/3 => Optimizing head pose and expressions using landmarks...
100%|█████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:04<00:00, 401.81it/s]
2/3 => Optimizing shape, statistical albedos, expression, head pose and scene light...
  0%|                                                                                          | 0/401 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "optimizer.py", line 495, in <module>
    doStep3= doStep3)
  File "optimizer.py", line 438, in run
    self.runStep2()
  File "optimizer.py", line 244, in runStep2
    images = self.pipeline.render(cameraVerts, diffuseTextures, specularTextures)
  File "C:\NextFace\pipeline.py", line 139, in render
    images = self.renderer.render(scenes)
  File "C:\NextFace\renderer.py", line 155, in render
    device = self.device)
  File "C:\NextFace\renderer.py", line 62, in renderPathTracing
    device=device)
  File "C:\NextFace\renderer.py", line 41, in rayTrace
    imgs.append(pyredner.RenderFunction.apply(se, *scene_args))
  File "C:\Users\user\anaconda3\envs\facenext\lib\site-packages\pyredner\render_pytorch.py", line 659, in forward
    args_ctx = RenderFunction.unpack_args(seed, args)
  File "C:\Users\user\anaconda3\envs\facenext\lib\site-packages\pyredner\render_pytorch.py", line 617, in unpack_args
    use_secondary_edge_sampling)
RuntimeError: Function "_rtpModelUpdate" caught exception: Encountered a CUDA error: radix_sort_temp_size -> cub::DeviceRadixSort::SortPairs returned (8): invalid device function
```

**Comment by MehmetOKUYAR** [comment]
ı have same problem

**Comment by Daves-ding** [comment]
same

**Comment by LitCaesala** [comment]
same, also win11, 4090

**Comment by wangalong-ahpu** [comment]
same
